package com.group10.qpj.settings.domain;

public class Client {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.c_id
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.c_name
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.c_password
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    private String cPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.c_phone
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    private String cPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.c_right
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    private Integer cRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.c_email
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    private String cEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.c_id
     *
     * @return the value of client.c_id
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.c_id
     *
     * @param cId the value for client.c_id
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.c_name
     *
     * @return the value of client.c_name
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.c_name
     *
     * @param cName the value for client.c_name
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.c_password
     *
     * @return the value of client.c_password
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public String getcPassword() {
        return cPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.c_password
     *
     * @param cPassword the value for client.c_password
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public void setcPassword(String cPassword) {
        this.cPassword = cPassword == null ? null : cPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.c_phone
     *
     * @return the value of client.c_phone
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.c_phone
     *
     * @param cPhone the value for client.c_phone
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.c_right
     *
     * @return the value of client.c_right
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public Integer getcRight() {
        return cRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.c_right
     *
     * @param cRight the value for client.c_right
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public void setcRight(Integer cRight) {
        this.cRight = cRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.c_email
     *
     * @return the value of client.c_email
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public String getcEmail() {
        return cEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.c_email
     *
     * @param cEmail the value for client.c_email
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    public void setcEmail(String cEmail) {
        this.cEmail = cEmail == null ? null : cEmail.trim();
    }
}