package com.group10.qpj.settings.mapper;

import com.group10.qpj.settings.domain.Client;

import java.util.Map;

public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    int insertSelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    Client selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    int updateByPrimaryKeySelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Wed Jun 01 19:14:21 CST 2022
     */
    int updateByPrimaryKey(Client record);

    /**
     * 根据账号密码查询用户
     * @param map
     * @return
     */
    Client selectUserByLoginActAndPwd(Map<String,Object> map);

    /**
     * 保存注册的客户信息
     * @param client
     * @return
     */
    int insertClient(Client client);
}